export const PROVINCES_DATA: Record<string, { name: string, districts: string[] }> = {
  'hanoi': { name: 'Hà Nội', districts: ['Ba Đình', 'Hoàn Kiếm', 'Tây Hồ', 'Long Biên', 'Cầu Giấy', 'Đống Đa', 'Hai Bà Trưng', 'Hoàng Mai', 'Thanh Xuân', 'Nam Từ Liêm', 'Bắc Từ Liêm', 'Hà Đông'] },
  'hcm': { name: 'TP. Hồ Chí Minh', districts: ['Quận 1', 'Quận 3', 'Quận 4', 'Quận 5', 'Quận 6', 'Quận 7', 'Quận 8', 'Quận 10', 'Quận 11', 'Quận 12', 'Bình Thạnh', 'Tân Bình', 'Tân Phú', 'Gò Vấp', 'Phú Nhuận', 'Thủ Đức', 'Bình Tân'] },
  'danang': { name: 'Đà Nẵng', districts: ['Hải Châu', 'Thanh Khê', 'Sơn Trà', 'Ngũ Hành Sơn', 'Liên Chiểu', 'Cẩm Lệ'] },
  'binhduong': { name: 'Bình Dương', districts: ['Thủ Dầu Một', 'Bến Cát', 'Dĩ An', 'Thuận An', 'Tân Uyên'] },
  'vungtau': { name: 'Bà Rịa - Vũng Tàu', districts: ['Vũng Tàu', 'Bà Rịa', 'Phú Mỹ', 'Châu Đức', 'Xuyên Mộc'] },
  'haiphong': { name: 'Hải Phòng', districts: ['Hồng Bàng', 'Lê Chân', 'Ngô Quyền', 'Kiến An', 'Hải An', 'Đồ Sơn'] },
  'cantho': { name: 'Cần Thơ', districts: ['Ninh Kiều', 'Bình Thủy', 'Cái Răng', 'Ô Môn', 'Thốt Nốt'] },
  'dongnai': { name: 'Đồng Nai', districts: ['Biên Hòa', 'Long Khánh', 'Long Thành', 'Nhơn Trạch'] },
  'quangninh': { name: 'Quảng Ninh', districts: ['Hạ Long', 'Cẩm Phả', 'Uông Bí', 'Móng Cái'] },
  'lamdong': { name: 'Lâm Đồng', districts: ['Đà Lạt', 'Bảo Lộc', 'Đức Trọng'] },
  'khanhhoa': { name: 'Khánh Hòa', districts: ['Nha Trang', 'Cam Ranh', 'Ninh Hòa'] },
  'daklak': { name: 'Đắk Lắk', districts: ['Buôn Ma Thuột', 'Buôn Hồ'] },
  'hue': { name: 'Thừa Thiên Huế', districts: ['Huế', 'Hương Thủy', 'Hương Trà'] },
  'nghean': { name: 'Nghệ An', districts: ['Vinh', 'Cửa Lò', 'Thái Hòa'] },
  'thanhhoa': { name: 'Thanh Hóa', districts: ['Thanh Hóa', 'Sầm Sơn', 'Bỉm Sơn'] },
  'bacninh': { name: 'Bắc Ninh', districts: ['Bắc Ninh', 'Từ Sơn', 'Gia Bình'] },
  'thainguyen': { name: 'Thái Nguyên', districts: ['Thái Nguyên', 'Sông Công', 'Phổ Yên'] },
  'phutho': { name: 'Phú Thọ', districts: ['Việt Trì', 'Phú Thọ'] },
  'vinhphuc': { name: 'Vĩnh Phúc', districts: ['Vĩnh Yên', 'Phúc Yên'] },
  'hungyen': { name: 'Hưng Yên', districts: ['Hưng Yên', 'Mỹ Hào'] },
  'hanam': { name: 'Hà Nam', districts: ['Phủ Lý', 'Duy Tiên'] },
  'namdinh': { name: 'Nam Định', districts: ['Nam Định'] },
  'thaibinh': { name: 'Thái Bình', districts: ['Thái Bình'] },
  'ninhbinh': { name: 'Ninh Bình', districts: ['Ninh Bình', 'Tam Điệp'] },
  'quangnam': { name: 'Quảng Nam', districts: ['Tam Kỳ', 'Hội An'] },
  'quangngai': { name: 'Quảng Ngãi', districts: ['Quảng Ngãi'] },
  'binhdinh': { name: 'Bình Định', districts: ['Quy Nhơn', 'An Nhơn'] },
  'phuyen': { name: 'Phú Yên', districts: ['Tuy Hòa', 'Sông Cầu'] },
  'ninhthuan': { name: 'Ninh Thuận', districts: ['Phan Rang - Tháp Chàm'] },
  'binhthuan': { name: 'Bình Thuận', districts: ['Phan Thiết', 'Lagi'] },
  'kontum': { name: 'Kon Tum', districts: ['Kon Tum'] },
  'gialai': { name: 'Gia Lai', districts: ['Pleiku', 'An Khê'] },
  'daknong': { name: 'Đắk Nông', districts: ['Gia Nghĩa'] },
  'tiengiang': { name: 'Tiền Giang', districts: ['Mỹ Tho', 'Gò Công'] },
};

export const CATEGORIES = [
  'Cơm văn phòng', 'Bún bò', 'Phở', 'Bún chả', 'Cafe', 'Ăn vặt', 'Miến/Mì/Miểng', 'Cơm tấm', 'Hải sản', 'Lẩu & Nướng', 'Quán nhậu', 'Sang trọng'
];
